export const SEARCH_ALBUMS = 'SEARCH_ALBUMS'
export const SET_CURRENT_ALBUM = "SET_CURRENT_ALBUM";
export const LOGIN = "LOGIN";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
